<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Http\Request;

class Contract extends Model
{
    protected $table = 'contract';

    const CREATED_AT = 'create_at';
    const UPDATED_AT = 'update_at';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'id',
        'mst_admin_id',
        'mst_company_id',
        'contract_fromdate',
        'contract_todate',
        'intro_type',
        'period_type',
        'contractupdate_type',
        'update_judgment',
        'contract_date_sheet',
        'basiccontract_fromdate',
        'basiccontract_todate',
        'comment',
        'dispatcharea_name',
        'office_name',
        'office_address',
        'department',
        'position',
        'employment_address',
        'employment_phone_no',
        'responsible_name',
        'responsible_phone_no',
        'commander_name',
        'commander_phone_no',
        'troubles_name',
        'troubles_phone_no',
        'fraction_type',
        'register_no',
        'name',
        'gender_type',
        'age',
        'personnel',
        'socialinsurance_fromdate',
        'socialinsurance_todate',
        'employmentinsurance_fromdate',
        'employmentinsurance_todate',
        'employmentcontract_date',
        'employmentconversion_date',
        'insured_certification',
        'employment_stabilization',
        'education',
        'career_consulting',
        'dispatch_education',
        'troubles_ledger',
        'dispatchsource_name',
        'source_address',
        'source_phone_no',
        'source_responsible_name',
        'source_responsible_phone_no',
        'business_permit_no',
        'troubles_sheet',
        'attendance_time',
        'leave_time',
        'break_time',
        'predetermined_time',
        'overtime',
        'paid_time',
        'workday_kbn',
        'mmax_overtime',
        'wmax_overtime',
        'wmax_workday',
        'request_deadline',
        'salary_deadline',
        'time_round_unit',
        'price_timeflat_type',
        'price_predetermined_time',
        'price_overtime',
        'price_holiday',
        'price_legal_holiday',
        'price_legal_midnight',
        'price_legal_holiday_midnight',
        'price_other',
        'price_month_overtime_flg',
        'price_month60',
        'price_month45',
        'wage_timeflat_type',
        'wage_predetermined_time',
        'wage_overtime',
        'wage_holiday',
        'wage_legal_holiday',
        'wage_legal_midnight',
        'wage_price_legal_holiday_midnight',
        'wage_other',
        'wage_month_overtime_flg',
        'wage_month60',
        'wage_month45',
        'con_working_style',
        'con_working_hours',
        'con_break_time',
        'con_contract_time',
        'business_content_kbn',
        'business_other',
        'organization_date',
        'organization_date_sheet',
        'office_date',
        'office_date_sheet',
        'dispatchperiod_type',
        'employmentperiod_type',
        'employmentworker_fromdate',
        'employmentworker_todate',
        'employmentworker_reason_type',
        'employmentworker_detail_type',
        'project_fromdate',
        'project_todate',
        'monthly_days',
        'monthly_workday',
        'closedwork_fromdate',
        'closedwork_todate',
        'worker_name',
        'workday_detail',
        'workday',
        'payment_terms',
        'wage_payment_terms',
        'contract_other',
        'staff_other',
        'overtime_terms',
        'holydaywork_terms',
        'holyday_terms',
        'health_safety_terms',
        'contract_cancel_dispatch',
        'contract_cancel_employment',
        'retirement',
        'welfare',
        'troubles_dispatch',
        'troubles_employment',
        'dispatch_fee',
        'dispatch36',
        'dispute_measures',
        'contract_deemed',
        'validity_period',
        'special_provisions',
        'remarks',
        'contract_period',
        'business_content',
        'work_place',
        'sh_breaktime',
        'sh_overwork',
        'sh_holyday',
        'sh_timeoff',
        'sh_wage',
        'extra_wage_rate',
        'welfarepension_type',
        'healthinsurance_type',
        'employmentinsurance_type',
        'accidentinsurance_type',
        'sheet_other',
        'introduction_dispatching',
        'offer_purpose',
        'result',
        'result_reason',
        'del_flg',
        'create_at',
        'create_user',
        'update_at',
        'update_user'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [ ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [  ];

    public function rules($id = 'null'){
        return [
            'contract_fromdate' => 'required|date',
            'contract_todate' => 'required|date',
            'intro_type' => 'nullable|numeric',
            'period_type' => 'nullable|numeric',
            'contractupdate_type' => 'nullable|numeric',
            'update_judgment' => 'nullable|max:256',
            'contract_date_sheet' => 'nullable|date',
            'basiccontract_fromdate' => 'nullable|date',
            'basiccontract_todate' => 'nullable|date',
            'comment' => 'nullable|max:256',
            'dispatcharea_name' => 'nullable|max:128',
            'office_name' => 'nullable|max:128',
            'office_address' => 'nullable|max:256',
            'department' => 'nullable|max:128',
            'position' => 'nullable|max:128',
            'employment_address' => 'nullable|max:256',
            'employment_phone_no' => 'nullable|max:15|regex:/^[0-9-]{0,15}$/',
            'responsible_name' => 'nullable|max:128',
            'responsible_phone_no' => 'nullable|max:15|regex:/^[0-9-]{0,15}$/',
            'commander_name' => 'nullable|max:128',
            'commander_phone_no' => 'nullable|max:15|regex:/^[0-9-]{0,15}$/',
            'troubles_name' => 'nullable|max:128',
            'troubles_phone_no' => 'nullable|max:15|regex:/^[0-9-]{0,15}$/',
            'fraction_type' => 'required|numeric',
            'register_no' => 'nullable|max:10',
            'name' => 'nullable|max:128',
            'gender_type' => 'nullable|numeric',
            'age' => 'nullable|numeric',
            'personnel' => 'nullable|max:64',
            'socialinsurance_fromdate' => 'nullable|date',
            'socialinsurance_todate' => 'nullable|date',
            'employmentinsurance_fromdate' => 'nullable|date',
            'employmentinsurance_todate' => 'nullable|date',
            'employmentcontract_date' => 'nullable|date',
            'employmentconversion_date' => 'nullable|date',
            'insured_certification' => 'nullable|max:256',
            'employment_stabilization' => 'nullable|max:256',
            'education' => 'nullable|max:256',
            'career_consulting' => 'nullable|max:256',
            'dispatch_education' => 'nullable|max:256',
            'troubles_ledger' => 'nullable|max:256',
            'dispatchsource_name' => 'nullable|max:128',
            'source_address' => 'nullable|max:256',
            'source_phone_no' => 'nullable|max:15|regex:/^[0-9-]{0,15}$/',
            'source_responsible_name' => 'nullable|max:128',
            'source_responsible_phone_no' => 'nullable|max:15|regex:/^[0-9-]{0,15}$/',
            'business_permit_no' => 'nullable|max:15',
            'troubles_sheet' => 'nullable|max:128',
            'attendance_time' => 'nullable|date_format:H:i',
            'leave_time' => 'nullable|max:5|date_format:H:i',
            'break_time' => 'nullable|max:5|date_format:H:i',
            'predetermined_time' => 'nullable|max:5|date_format:H:i',
            'overtime' => 'nullable|max:5|date_format:H:i',
            'paid_time' => 'nullable|max:5|date_format:H:i',
            'workday_kbn' => 'nullable|numeric',
            'mmax_overtime' => 'nullable|numeric',
            'wmax_overtime' => 'nullable|numeric',
            'wmax_workday' => 'nullable|numeric',
            'request_deadline' => 'nullable|numeric',
            'salary_deadline' => 'nullable|numeric',
            'time_round_unit' => 'nullable|numeric',
            'price_timeflat_type' => 'nullable|numeric',
            'price_predetermined_time' => 'nullable|numeric',
            'price_overtime' => 'nullable|numeric',
            'price_holiday' => 'nullable|numeric',
            'price_legal_holiday' => 'nullable|numeric',
            'price_legal_midnight' => 'nullable|numeric',
            'price_price_legal_holiday_midnight' => 'nullable|numeric',
            'price_other' => 'nullable|numeric',
            'price_month_overtime_flg' => 'nullable|numeric',
            'price_month60' => 'nullable|numeric',
            'price_month45' => 'nullable|numeric',
            'wage_timeflat_type' => 'nullable|numeric',
            'wage_predetermined_time' => 'nullable|numeric',
            'wage_overtime' => 'nullable|numeric',
            'wage_holiday' => 'nullable|numeric',
            'wage_legal_holiday' => 'nullable|numeric',
            'wage_legal_midnight' => 'nullable|numeric',
            'wage_legal_holiday_midnight' => 'nullable|numeric',
            'wage_other' => 'nullable|numeric',
            'wage_month_overtime_flg' => 'nullable|numeric',
            'wage_month60' => 'nullable|numeric',
            'wage_month45' => 'nullable|numeric',
            'con_working_style' => 'nullable|max:256',
            'con_working_hours' => 'nullable|max:256',
            'con_break_time' => 'nullable|max:256',
            'con_contract_time' => 'nullable|max:256',
            'business_content_kbn' => 'nullable|numeric',
            'business_other' => 'nullable|max:256',
            'organization_date' => 'nullable|date',
            'organization_date_sheet' => 'nullable|date',
            'office_date' => 'nullable|date',
            'office_date_sheet' => 'nullable|date',
            'dispatchperiod_type' => 'nullable|numeric',
            'employmentperiod_type' => 'nullable|numeric',
            'employmentworker_fromdate' => 'nullable|date',
            'employmentworker_todate' => 'nullable|date',
            'employmentworker_reason_type' => 'nullable|numeric',
            'employmentworker_detail_type' => 'nullable|numeric',
            'project_fromdate' => 'nullable|date',
            'project_todate' => 'nullable|date',
            'monthly_days' => 'nullable|numeric',
            'monthly_workday' => 'nullable|numeric',
            'closedwork_fromdate' => 'nullable|date',
            'closedwork_todate' => 'nullable|date',
            'worker_name' => 'nullable|max:256',
            'workday_detail' => 'nullable|max:256',
            'workday' => 'nullable|max:256',
            'payment_terms' => 'nullable|max:256',
            'wage_payment_terms' => 'nullable|max:256',
            'contract_other' => 'nullable|max:256',
            'staff_other' => 'nullable|max:256',
            'overtime_terms' => 'nullable|max:256',
            'holydaywork_terms' => 'nullable|max:256',
            'holyday_terms' => 'nullable|max:256',
            'health_safety_terms' => 'nullable|max:256',
            'contract_cancel_dispatch' => 'nullable|max:512',
            'contract_cancel_employment' => 'nullable|max:256',
            'retirement' => 'nullable|max:256',
            'welfare' => 'nullable|max:256',
            'troubles_dispatch' => 'nullable|max:256',
            'troubles_employment' => 'nullable|max:256',
            'dispatch_fee' => 'nullable|max:256',
            'dispatch36' => 'nullable|max:256',
            'dispute_measures' => 'nullable|max:256',
            'contract_deemed' => 'nullable|max:256',
            'validity_period' => 'nullable|max:256',
            'special_provisions' => 'nullable|max:256',
            'remarks' => 'nullable|max:256',
            'contract_period' => 'nullable|max:128',
            'business_content' => 'nullable|max:128',
            'work_place' => 'nullable|max:128',
            'sh_breaktime' => 'nullable|max:128',
            'sh_overwork' => 'nullable|max:128',
            'sh_holyday' => 'nullable|max:128',
            'sh_timeoff' => 'nullable|max:128',
            'sh_wage' => 'nullable|max:128',
            'extra_wage_rate' => 'nullable|max:128',
            'welfarepension_type' => 'nullable|numeric',
            'healthinsurance_type' => 'nullable|numeric',
            'employmentinsurance_type' => 'nullable|numeric',
            'accidentinsurance_type' => 'nullable|numeric',
            'sheet_other' => 'nullable|max:128',
            'introduction_dispatching' => 'nullable|max:128',
            'offer_purpose' => 'nullable|max:128',
            'result' => 'nullable|max:128',
            'result_reason' => 'nullable|max:256',   
        ];
    }
    public function messages()
    {
        return [
            'attendance_time.date_format' => ':attribute は、00:00形式で入力してください。',
            'leave_time.date_format' => ':attribute は、00:00形式で入力してください。',
            'break_time.date_format' => ':attribute は、00:00形式で入力してください。',
            'predetermined_time.date_format' => ':attribute は、00:00形式で入力してください。',
            'overtime.date_format' => ':attribute は、00:00形式で入力してください。',
            'paid_time.date_format' => ':attribute は、00:00形式で入力してください。',
            'employment_phone_no.regex'=>':attribute は、0000-0000-0000形式で入力してください。',
            'responsible_phone_no.regex'=>':attribute は、TEL　0000-0000-0000形式で入力してください。',
            'commander_phone_no.regex'=>':attribute は、0000-0000-0000形式で入力してください。',
            'troubles_phone_no.regex'=>':attribute は、0000-0000-0000形式で入力してください。',
            'source_phone_no.regex'=>':attribute は、0000-0000-0000形式で入力してください。',
            'source_responsible_phone_no.regex'=>':attribute は、0000-0000-0000形式で入力してください。',
        ];
    }
    public function attributes(): array
    {
        return [
            'id' => '契約ID',
            'mst_admin_id' => '作成者ID',
            'mst_company_id' => '作成会社ID',
            'contract_fromdate' => '管理用：派遣開始日',
            'contract_todate' => '管理用：派遣終了日',
            'intro_type' => '管理用：紹介派遣か否かの別',
            'period_type' => '管理用：期間の定め',
            'contractupdate_type' => '管理用：契約更新の有無',
            'update_judgment' => '管理用：契約の更新の判断基準',
            'contract_date_sheet' => '管理用：契約日(帳票用)',
            'basiccontract_fromdate' => '管理用：基本契約開始日',
            'basiccontract_todate' => '管理用：基本契約終了日',
            'comment' => '管理用：コメント',
            'dispatcharea_name' => '派遣先：派遣先名',
            'office_name' => '派遣先：事業所名',
            'office_address' => '派遣先：事業所住所',
            'department' => '派遣先：部署名',
            'position' => '派遣先：部署長役職',
            'employment_address' => '派遣先：就業先所在地',
            'employment_phone_no' => '派遣先：就業先TEL',
            'responsible_name' => '派遣先：責任者',
            'responsible_phone_no' => '派遣先：責任者TEL',
            'commander_name' => '派遣先：指揮命令者',
            'commander_phone_no' => '派遣先：指揮命令者TEL',
            'troubles_name' => '派遣先：苦情処理の申出先',
            'troubles_phone_no' => '派遣先：苦情処理の申出先TEL',
            'fraction_type' => '派遣先：1円未満端数処理',
            'register_no' => 'スタッフ：人材登録番号',
            'name' => 'スタッフ：氏名',
            'gender_type' => 'スタッフ：性別',
            'age' => 'スタッフ：年齢',
            'personnel' => 'スタッフ：派遣人員',
            'socialinsurance_fromdate' => 'スタッフ：社会保険加入日',
            'socialinsurance_todate' => 'スタッフ：社会保険喪失日',
            'employmentinsurance_fromdate' => 'スタッフ：雇用保険加入日',
            'employmentinsurance_todate' => 'スタッフ：雇用保険喪失日',
            'employmentcontract_date' => 'スタッフ：有期雇用契約雇入れ日',
            'employmentconversion_date' => 'スタッフ：有期雇用転換日',
            'insured_certification' => 'スタッフ：被保険者資格取得の有無',
            'employment_stabilization' => 'スタッフ：雇用安定措置(管理台帳)',
            'education' => 'スタッフ：教育訓練の状況(管理台帳)',
            'career_consulting' => 'スタッフ：キャリアコンサルティングの実施状況(管理台帳)',
            'dispatch_education' => 'スタッフ：派遣先での教育訓練の状況(管理台帳)',
            'troubles_ledger' => 'スタッフ：苦情処理状況(管理台帳)',
            'dispatchsource_name' => '派遣元：名称',
            'source_address' => '派遣元：所在地',
            'source_phone_no' => '派遣元：所在地TEL',
            'source_responsible_name' => '派遣元：責任者',
            'source_responsible_phone_no' => '派遣元：責任者TEL',
            'business_permit_no' => '派遣元：事業許可番号',
            'troubles_sheet' => '派遣元：苦情処理の申出先(帳票用)',
            'attendance_time' => '計算項目：出社',
            'leave_time' => '計算項目：退社',
            'break_time' => '計算項目：休憩',
            'predetermined_time' => '計算項目：所定',
            'overtime' => '計算項目：残業基準',
            'paid_time' => '計算項目：有給日時間数',
            'workday_kbn' => '計算項目：出勤曜日',
            'mmax_overtime' => '計算項目：月最大時間外労働',
            'wmax_overtime' => '計算項目：最大週時間外労働',
            'wmax_workday' => '計算項目：最大週勤務日数',
            'request_deadline' => '計算項目：請求計算締日',
            'salary_deadline' => '計算項目：給与計算締日',
            'time_round_unit' => '計算項目：時間丸め単位',
            'price_timeflat_type' => '計算項目：料金_時間制定額制',
            'price_predetermined_time' => '計算項目：料金_所定時間',
            'price_overtime' => '計算項目：料金_時間外',
            'price_holiday' => '計算項目：料金_休日出勤',
            'price_legal_holiday' => '計算項目：料金_法定休日出勤',
            'price_legal_midnight' => '計算項目：料金_法定内深夜',
            'price_price_legal_holiday_midnight' => '計算項目：料金_法定休日深夜',
            'price_other' => '計算項目：料金_その他',
            'price_month_overtime_flg' => '計算項目：料金_1か月の時間外労働による割増料金を適用する',
            'price_month60' => '計算項目：料金_月60時間超過',
            'price_month45' => '計算項目：料金_月45時間超過',
            'wage_timeflat_type' => '計算項目：賃金_時間制定額制',
            'wage_predetermined_time' => '計算項目：賃金_所定時間',
            'wage_overtime' => '計算項目：賃金_時間外',
            'wage_holiday' => '計算項目：賃金_休日出勤',
            'wage_legal_holiday' => '計算項目：賃金_法定休日出勤',
            'wage_legal_midnight' => '計算項目：賃金_法定内深夜',
            'wage_legal_holiday_midnight' => '計算項目：賃金_法定休日深夜',
            'wage_other' => '計算項目：賃金_その他',
            'wage_month_overtime_flg' => '計算項目：賃金_1か月の時間外労働による割増料金を適用する',
            'wage_month60' => '計算項目：賃金_月60時間超過',
            'wage_month45' => '計算項目：賃金_月45時間超過',
            'con_working_style' => '派遣条件：就業形態',
            'con_working_hours' => '派遣条件：就業時間',
            'con_break_time' => '派遣条件：休憩時間',
            'con_contract_time' => '派遣条件：契約時間',
            'business_content_kbn' => '派遣条件：業務内容',
            'business_other' => '派遣条件：業務内容(詳細その他)',
            'organization_date' => '派遣条件：組織単位抵触日',
            'organization_date_sheet' => '派遣条件：組織単位抵触日_帳票用',
            'office_date' => '派遣条件：事業所抵触日',
            'office_date_sheet' => '派遣条件：事業所抵触日_帳票用',
            'dispatchperiod_type' => '派遣条件：派遣期間制限',
            'employmentperiod_type' => '派遣条件：雇用期間の定め有無',
            'employmentworker_fromdate' => '派遣条件：有期雇用派遣労働者_開始日',
            'employmentworker_todate' => '派遣条件：有期雇用派遣労働者_終了日',
            'employmentworker_reason_type' => '派遣条件：派遣条件：無期雇用派遣労働者－理由',
            'employmentworker_detail_type' => '派遣条件：派遣条件：無期雇用派遣労働者－詳細',
            'project_fromdate' => '派遣条件：有期プロジェクト業務_開始日',
            'project_todate' => '派遣条件：有期プロジェクト業務_終了日',
            'monthly_days' => '派遣条件：１か月間に行われる日数',
            'monthly_workday' => '派遣条件：通常の労働者の１か月間の所定労働日数',
            'closedwork_fromdate' => '派遣条件：産前・産後・育児・介護休業業務_開始日',
            'closedwork_todate' => '派遣条件：産前・産後・育児・介護休業業務_終了日',
            'worker_name' => '派遣条件：業務労働者名',
            'workday_detail' => '派遣条件：就業日の詳細',
            'workday' => '派遣条件：就業日',
            'payment_terms' => '派遣条件：料金支払条件',
            'wage_payment_terms' => '派遣条件：賃金支払条件',
            'contract_other' => '派遣条件：派遣先契約内容その他（派遣契約書)',
            'staff_other' => '派遣条件：スタッフ契約内容その他（雇入通知書)',
            'overtime_terms' => '派遣条件：時間外労働',
            'holydaywork_terms' => '派遣条件：休日労働',
            'holyday_terms' => '派遣条件：休日',
            'health_safety_terms' => '派遣条件：安全・衛生',
            'contract_cancel_dispatch' => '派遣条件：契約解除の措置（派遣契約書)',
            'contract_cancel_employment' => '派遣条件：契約解除の措置（雇入通知書)',
            'retirement' => '派遣条件：退職に関する事項',
            'welfare' => '派遣条件：福利厚生等',
            'troubles_dispatch' => '派遣条件：苦情処理事項（派遣契約書)',
            'troubles_employment' => '派遣条件：苦情処理事項（雇入通知書)',
            'dispatch_fee' => '派遣条件：派遣料金の明示',
            'dispatch36' => '派遣条件：派遣元36協定',
            'dispute_measures' => '派遣条件：派遣先が派遣労働者を雇用する場合の紛争措置',
            'contract_deemed' => '派遣条件：労働契約みなし制度',
            'validity_period' => '派遣条件：有効期間の日程',
            'special_provisions' => '派遣条件：特別条項',
            'remarks' => '派遣条件：備考',
            'contract_period' => '契約帳票：契約期間',
            'business_content' => '契約帳票：業務内容',
            'work_place' => '契約帳票：就業場所',
            'sh_breaktime' => '契約帳票：休憩時間',
            'sh_overwork' => '契約帳票：所定時間外労働',
            'sh_holyday' => '契約帳票：休日',
            'sh_timeoff' => '契約帳票：休暇',
            'sh_wage' => '契約帳票：賃金',
            'extra_wage_rate' => '契約帳票：割増賃金率',
            'welfarepension_type' => '契約帳票：厚生年金',
            'healthinsurance_type' => '契約帳票：健康保険',
            'employmentinsurance_type' => '契約帳票：雇用保険',
            'accidentinsurance_type' => '契約帳票：労災保険',
            'sheet_other' => '契約帳票：その他',
            'introduction_dispatching' => '管理台帳：紹介予定派遣である旨',
            'offer_purpose' => '管理台帳：求人・求職の意思確認',
            'result' => '管理台帳：採否結果',
            'result_reason' => '管理台帳：採否結果の理由',          
        ];
    }
}
