export const CIRCULAR_USER = {
    NOT_NOTIFY_STATUS: 0,
    NOTIFIED_UNREAD_STATUS: 1,
    READ_STATUS: 2,
    APPROVED_WITH_STAMP_STATUS: 3,
    APPROVED_WITHOUT_STAMP_STATUS: 4,
    SEND_BACK_STATUS: 5,
    END_OF_REQUEST_SEND_BACK: 6,
    SUBMIT_REQUEST_SEND_BACK: 7,
    PULL_BACK_TO_USER_STATUS: 8,
    REVIEWING_STATUS: 10,
    NODE_COMPLETED_STATUS: 11,
};