export const CIRCULAR = {
    SAVING_STATUS: 0,
    CIRCULATING_STATUS: 1,
    CIRCULAR_COMPLETED_STATUS: 2,
    CIRCULAR_COMPLETED_SAVED_STATUS: 3,
    SEND_BACK_STATUS: 4,
    RETRACTION_STATUS: 5,
    DELETE_STATUS: 9,
};