export const EXPENSE = {
    M_FORM_FORM_TYPE_ADVANCE: 1,
    M_FORM_FORM_TYPE_SETTLEMENT: 2,
    T_APP_STATUS_CIRCULATING: [1],
    T_APP_STATUS_BEFORE_CIRCULAR: [0, 4],
    T_APP_STATUS_AFTER_CIRCULAR: [2, 3],

    M_WTSM_NUM_PEOPLE_OPTION_NONE: 0,
    M_WTSM_DETAIL_OPTION_NONE: 0,
    M_WTSM_VOUCHER_OPTION_NONE: 0,
    M_WTSM_VOUCHER_OPTION_REQUIRE: 1,
    M_WTSM_TAX_OPTION_NONE: 0,

    EPS_T_APP_ITEMS_ROUNDTRIP_FLAG_DEFAULT: 0,
    EPS_T_APP_ITEMS_SUBMIT_METHOD_DEFAULT: 1,
    EPS_T_APP_ITEMS_NONSUBMIT_TYPE_DEFAULT: 0,

    T_APP_STATUS_DISPLAY: {
        0: '回覧前',
        1: '回覧中',
        2: '回覧完了',
        3: '回覧完了',
        4: '差戻し',
    }
};
