export const PORTAL_COMPONENT = {
    FAVORITE: "favorite",
    SCHEDULER: "scheduler",
    BULLETIN_BOARD: "bulletin_board",
    CIRCULAR: "circular",
    TIME_CARD: "time_card",
    TIME_CARD_ATTENDANCE: "time_card_attendance",
    FILE_MAIL: "file_mail",
    SPECIAL: "special",
    TOP_MENU: "top_menu",
    TOP_SCREEN: "top_screen",
    NOTIFICATION: "notification",
    MOVIE: "movie",
    ADVERTISEMENT: "advertisement",
    CUSTOMIZE_AREA: 'customize_area',
    FAQ_BULLETIN_BOARD: "faq_bulletin_board",
    RECEIVE_PLAN: "receive_plan",
    TO_DO_LIST: "to_do_list",
};
